### ISSUE TITLE
FeitCSI-iwlwifi breaks other wireless drivers

### ISSUE THREAD

**Issue by ddodds-nlplogix** [KuskoSoft/FeitCSI-iwlwifi#1] opened 2024-04-29 21:51 UTC
Hello, my team and I are trying to use FeitCSI to research the applications of Channel State Information using the AX210s. The changes made to the mac80211 interface are breaking other wireless drivers. We are attempting to set up FeitCSI on the Raspberry Pi 5 using the PCIe Wi-Fi 6E Hat by MCUZone and the Intel AX210. 

I've tested Intel's iwlwifi drivers and confirmed the chip works on the Pi5. FeitCSI compiles and installs properly on the Pi5 using Ubuntu 24.04. However, when attempting to connect the Pi5's built-in wireless chip, the dmesg log is flooded with missing symbol errors from the brcmfmac and brcmsmac modules referring to files defined by the mac80211 module.

We attempted to reproduce this setup on a laptop with an ax210 chip, which we've again, confirmed to be working using the iwlwifi drivers by Intel. The modified drivers appear to show the wifi chip in the interface, but the USB Wi-Fi dongle's driver, 88x2bu, we're attempting to use, begins to report missing symbol files.

We're trying to create a device that transmits data using one chip and monitors CSI data on the other.

Below is the error log associated to the 88x2bu driver regarding the 80211 driver. The Raspberrry pi 5's brcmfmac and brcmsmac logs look about the same, if I still had them available I'd post them here, but thought this was sufficient.

If there is anything that you need help with to get this functioning, please let me know. I do not mind making contributions.

> [    2.095863] 88x2bu: disagrees about version of symbol cfg80211_del_sta_sinfo
> [    2.095866] 88x2bu: Unknown symbol cfg80211_del_sta_sinfo (err -22)
> [    2.095893] 88x2bu: disagrees about version of symbol cfg80211_vendor_cmd_reply
> [    2.095894] 88x2bu: Unknown symbol cfg80211_vendor_cmd_reply (err -22)
> [    2.095907] 88x2bu: disagrees about version of symbol cfg80211_ibss_joined
> [    2.095908] 88x2bu: Unknown symbol cfg80211_ibss_joined (err -22)
> [    2.095914] 88x2bu: disagrees about version of symbol __cfg80211_get_bss
> [    2.095915] 88x2bu: Unknown symbol __cfg80211_get_bss (err -22)
> [    2.095930] 88x2bu: disagrees about version of symbol cfg80211_ch_switch_notify
> [    2.095931] 88x2bu: Unknown symbol cfg80211_ch_switch_notify (err -22)
> [    2.095939] 88x2bu: disagrees about version of symbol ieee80211_get_channel_khz
> [    2.095940] 88x2bu: Unknown symbol ieee80211_get_channel_khz (err -22)
> [    2.095952] 88x2bu: disagrees about version of symbol cfg80211_ready_on_channel
> [    2.095953] 88x2bu: Unknown symbol cfg80211_ready_on_channel (err -22)
> [    2.095955] 88x2bu: disagrees about version of symbol cfg80211_inform_bss_frame_data
> [    2.095956] 88x2bu: Unknown symbol cfg80211_inform_bss_frame_data (err -22)
> [    2.095968] 88x2bu: disagrees about version of symbol cfg80211_scan_done
> [    2.095970] 88x2bu: Unknown symbol cfg80211_scan_done (err -22)
> [    2.095973] 88x2bu: disagrees about version of symbol __cfg80211_alloc_reply_skb
> [    2.095975] 88x2bu: Unknown symbol __cfg80211_alloc_reply_skb (err -22)
> [    2.095977] 88x2bu: disagrees about version of symbol cfg80211_new_sta
> [    2.095978] 88x2bu: Unknown symbol cfg80211_new_sta (err -22)
> [    2.095984] 88x2bu: disagrees about version of symbol wiphy_new_nm
> [    2.095985] 88x2bu: Unknown symbol wiphy_new_nm (err -22)
> [    2.095992] 88x2bu: disagrees about version of symbol cfg80211_roamed
> [    2.095993] 88x2bu: Unknown symbol cfg80211_roamed (err -22)
> [    2.095999] 88x2bu: disagrees about version of symbol cfg80211_mgmt_tx_status_ext
> [    2.096000] 88x2bu: Unknown symbol cfg80211_mgmt_tx_status_ext (err -22)
> [    2.096009] 88x2bu: disagrees about version of symbol wiphy_unregister
> [    2.096010] 88x2bu: Unknown symbol wiphy_unregister (err -22)
> [    2.096013] 88x2bu: disagrees about version of symbol cfg80211_remain_on_channel_expired
> [    2.096014] 88x2bu: Unknown symbol cfg80211_remain_on_channel_expired (err -22)
> [    2.096035] 88x2bu: disagrees about version of symbol cfg80211_put_bss
> [    2.096036] 88x2bu: Unknown symbol cfg80211_put_bss (err -22)
> [    2.096040] 88x2bu: disagrees about version of symbol cfg80211_rx_mgmt_ext
> [    2.096041] 88x2bu: Unknown symbol cfg80211_rx_mgmt_ext (err -22)
> [    2.096047] 88x2bu: disagrees about version of symbol cfg80211_unlink_bss
> [    2.096048] 88x2bu: Unknown symbol cfg80211_unlink_bss (err -22)
> [    2.096059] 88x2bu: disagrees about version of symbol cfg80211_disconnected
> [    2.096060] 88x2bu: Unknown symbol cfg80211_disconnected (err -22)
> [    2.096070] 88x2bu: disagrees about version of symbol __cfg80211_send_event_skb
> [    2.096071] 88x2bu: Unknown symbol __cfg80211_send_event_skb (err -22)
> [    2.096075] 88x2bu: disagrees about version of symbol cfg80211_michael_mic_failure
> [    2.096076] 88x2bu: Unknown symbol cfg80211_michael_mic_failure (err -22)
> [    2.096086] 88x2bu: disagrees about version of symbol cfg80211_external_auth_request
> [    2.096087] 88x2bu: Unknown symbol cfg80211_external_auth_request (err -22)
> [    2.096091] 88x2bu: disagrees about version of symbol cfg80211_connect_done
> [    2.096092] 88x2bu: Unknown symbol cfg80211_connect_done (err -22)
> [    2.096115] 88x2bu: disagrees about version of symbol wiphy_register
> [    2.096116] 88x2bu: Unknown symbol wiphy_register (err -22)
> [    2.096118] 88x2bu: disagrees about version of symbol wiphy_free
> [    2.096119] 88x2bu: Unknown symbol wiphy_free (err -22)
> [    2.096141] 88x2bu: disagrees about version of symbol cfg80211_ch_switch_started_notify
> [    2.096142] 88x2bu: Unknown symbol cfg80211_ch_switch_started_notify (err -22)
> [    2.096149] 88x2bu: disagrees about version of symbol __cfg80211_alloc_event_skb
> [    2.096150] 88x2bu: Unknown symbol __cfg80211_alloc_event_skb (err -22)

Thank you for your project!

**Comment by KuskoSoft** [comment] 2024-04-30 22:26
Hello @ddodds-nlplogix ,

first we can try to fix in laptop (and I hope that it will fix also Pi5). When you wrote "FeitCSI compiles and installs properly" you mean also that FeitCSI run correctly and you can measure CSI but you can't then used USB Wi-Fi dongle? Or you mean that you can't run FeitCSI neither USB Wi-Fi dongle?

Can you provide me output of `uname -a` and output of `sudo modinfo mac80211` but with loaded Intel's iwlwifi where USB Wi-Fi dongle worked. Thank you

**Comment by ddodds-nlplogix** [comment] 2024-05-01 14:30
> but you can't then used USB Wi-Fi dongle? Or you mean that you

Hey kuskosoft, thanks for the reply! By "FeitCSI works" I mean:

**What works:**
I can get FeitCSI compiled and installed, and even run the GUI. I can get measurements through the GUI. In addition, the network interface associated with the AX210 and the feitcsi-iwlwifi driver, just works for sending/receiving in general. 

**What does not work:**
Other chips are incapable of sending, receiving, connecting, or even displaying a network interface with ` ip a` as long as the feitcsi iwlwifi drivers are installed. Other chips function as intended with the kernel's version of iwliwifi. 

I will get you the output of those other commands in a bit, i have to get the laptop from my coworker to get that information.

**Comment by ddodds-nlplogix** [comment] 2024-05-01 16:26
The output of `uname -r` or the kernel version is
`6.8.0-31-generic` (comes with ubuntu 24.0)

The output of `sudo modinfo mac80211` is

```
nlplogix@lt-1:~$ sudo modinfo mac80211
filename:       /lib/modules/6.8.0-31-generic/kernel/net/mac80211/mac80211.ko.zst
license:        GPL
description:    IEEE 802.11 subsystem
srcversion:     B64ACC886876782FBE75414
depends:        cfg80211,libarc4
retpoline:      Y
intree:         Y
name:           mac80211
vermagic:       6.8.0-31-generic SMP preempt mod_unload modversions 
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        1F:7C:FE:B7:AF:4A:58:ED:AE:19:F1:11:33:2F:0E:CE:FD:5C:DE:73
sig_hashalgo:   sha512
signature:      6A:86:52:F0:38:BA:AC:33:7A:D4:96:23:C0:0E:33:E8:63:EB:D9:0B:
		69:E2:D2:CA:35:8E:09:A2:B1:4B:5B:B8:70:00:B0:E4:3D:62:7A:89:
		1F:70:61:8E:BA:81:FB:D1:60:A4:46:20:D1:0C:4F:F9:9A:70:05:53:
		3F:11:26:3B:D2:60:09:9D:C8:82:B2:EC:F1:30:F1:5E:86:AD:8C:F3:
		C0:94:A4:9F:85:66:7C:35:E8:91:E2:AA:F3:07:6C:EE:96:D0:50:06:
		B2:E0:51:E2:44:06:DC:22:49:92:90:89:96:D8:DA:F5:DE:DC:A7:7D:
		C2:89:1B:B9:74:4E:A7:1E:38:BF:5C:C7:9B:05:14:05:07:34:B1:DF:
		B0:A2:98:E7:2E:10:86:B0:39:2B:C9:73:3C:6B:FB:C6:33:4C:F3:58:
		88:11:F1:06:62:C4:91:2E:B4:C8:E0:8A:31:84:F9:07:E7:56:77:DC:
		F5:EC:7E:B7:93:61:6F:3D:E7:E7:B0:3B:E2:48:16:DA:57:E6:E3:33:
		71:AE:DC:9E:56:6A:67:5D:86:AD:60:FE:C2:E7:11:44:E8:F7:BF:74:
		BF:72:EE:23:EB:5C:13:27:82:9E:99:11:42:33:A8:BA:C1:2D:F9:CF:
		4D:C3:97:39:0B:AD:90:08:DC:A7:F5:34:67:2A:82:EA:D8:EF:90:F0:
		E4:B2:39:88:E1:C6:09:98:5E:E1:28:77:0C:4D:12:DD:C9:B5:2C:A2:
		E4:12:C4:E2:A8:E1:F2:20:59:2B:D2:C7:2A:C0:08:8D:89:40:CD:E1:
		70:58:35:D5:4F:5D:04:B6:7F:1A:BD:46:05:11:01:59:4B:B7:E7:9F:
		4B:76:9D:6E:A0:2C:83:AA:E4:E1:2F:F7:E1:83:8A:55:5D:AF:2F:D8:
		B6:56:ED:22:FE:59:94:84:93:11:7B:A5:DE:43:4B:FD:6F:CD:F5:2B:
		41:DC:8E:17:3F:77:11:16:67:73:51:F9:32:59:AA:4C:26:7E:74:0C:
		AC:F9:12:F8:E3:DC:FA:7A:51:22:FC:D8:18:9B:3F:35:0E:90:4F:A5:
		F3:CC:B8:74:A2:FD:9F:DD:FC:4A:F1:7F:2A:B7:77:09:67:2F:99:A3:
		D0:08:45:DC:1C:74:6E:CF:BF:ED:0B:05:F2:9D:89:03:37:BE:DD:6D:
		4A:55:6D:1D:98:71:26:56:B5:4C:50:86:DE:71:D8:F9:AB:6B:55:52:
		A0:02:52:3F:E6:58:6B:C1:18:8E:65:09:55:99:82:E3:E1:4D:9A:C1:
		63:9B:5D:CB:1D:5E:62:1A:50:65:9A:5D:77:C7:AE:03:3B:A3:A0:5C:
		86:7C:3F:E0:1E:49:E0:AE:31:0C:32:9C
parm:           minstrel_vht_only:Use only VHT rates when VHT is supported by sta. (bool)
parm:           max_nullfunc_tries:Maximum nullfunc tx tries before disconnecting (reason 4). (int)
parm:           max_probe_tries:Maximum probe tries before disconnecting (reason 4). (int)
parm:           beacon_loss_count:Number of beacon intervals before we decide beacon was lost. (int)
parm:           probe_wait_ms:Maximum time(ms) to wait for probe response before disconnecting (reason 4). (int)
parm:           ieee80211_default_rc_algo:Default rate control algorithm for mac80211 to use (charp)
```

**Comment by KuskoSoft** [comment] 2024-05-06 17:22
Hello @ddodds-nlplogix ,

the problem is [general with iwlwifi backport](https://bugzilla.kernel.org/show_bug.cgi?id=205573) which shipping a cfg80211 module. Your USB driver is compiled against kernel version of cfg80211. It is impossible compile FeitCSI-iwlwifi (customized iwlwifi backport) with kernel version of cfg80211 because e.g. your current kernel uses cfg80211 and iwlwifi with version X and FeitCSI uses cfg80211 and iwlwifi with version Y. So there is incompatibility.

If you want to run both USB WiFi and FeitCSI  on one device I suggest you to run USB WiFi on host and for FeitCSI you can use [virtual machine](https://feitcsi.kuskosoft.com/virt_manager/) or vice versa.

**Comment by ddodds-nlplogix** [comment] 2024-05-07 13:47
> Hello @ddodds-nlplogix ,
> 
> the problem is [general with iwlwifi backport](https://bugzilla.kernel.org/show_bug.cgi?id=205573) which shipping a cfg80211 module. Your USB driver is compiled against kernel version of cfg80211. It is impossible compile FeitCSI-iwlwifi (customized iwlwifi backport) with kernel version of cfg80211 because e.g. your current kernel uses cfg80211 and iwlwifi with version X and FeitCSI uses cfg80211 and iwlwifi with version Y. So there is incompatibility.
> 
> If you want to run both USB WiFi and FeitCSI on one device I suggest you to run USB WiFi on host and for FeitCSI you can use [virtual machine](https://feitcsi.kuskosoft.com/virt_manager/) or vice versa.

Based on this response, we got things working on the Raspberry Pi5, but the RPi5 does not support IOMMU, so PCIe Passthrough is not possible. You cannot passthrough either the ax210 nor the onboard WiFi chip from the RPi to a Virtual Machine. You can however, use USB passthrough which allows you to pass through a USB wireless card from the pi to the virtual machine and use that for data transmission.

Essentially, you can create an ssh conection from the virtual machine to the pi over the virtual ethernet bridge. Take CSI data from the pi, and put it on the VM, transfer the data off the VM to external source using a USB Wireless Stick. It appears this is the only possible way to get a second wifi chip on the pi using a virtual machine at this time.

**Comment by KuskoSoft** [comment] 2024-05-07 19:56
Thank you for your solution, I hope that it helps other people with same problem. I will think about solution to handle this problem but I think it will be impossible to cover all major distros kernel in general.

**Comment by ddodds-nlplogix** [comment] 2024-05-07 21:35
> Thank you for your solution, I hope that it helps other people with same problem. I will think about solution to handle this problem but I think it will be impossible to cover all major distros kernel in general.

Is there a chance that another USB wireless card on the market might support the same kernel  as feitcsi-iwlwifi. We do not have to use this specific usb device.

**Comment by KuskoSoft** [comment] 2024-05-08 08:12
> Is there a chance that another USB wireless card on the market might support the same kernel as feitcsi-iwlwifi. We do not have to use this specific usb device.

"same kernel as feitcsi-iwlwifi" is little bit misinformation because in general you can compile FeitCSI on different kernel versions.  The problem is that some modules e.g. cfg80211 is shipped with FeitCSI (modified iwlwifi-backport).

Solution will be compile drivers in your case 88x2bu against FeitCSIs cfg80211 etc. modules. Then it will work both FeitCSI and 88x2bu.

**Comment by ddodds-nlplogix** [comment] 2024-05-13 17:37
This makes a lot of sense, but also seems a bit time-consuming. I will let you know if I manage to get a setup working as you just explain. However, it probably won't be for a few weeks that I even attempt to do this, as the hours I can dedicate to our research is not decided by me. You can close this issue if you'd like and I can open another one if I get around to compiling drivers against FeitCSI to report back to you if we get it working.

**Comment by KuskoSoft** [comment] 2024-05-15 15:02
Hello @ddodds-nlplogix , ok I will close the issue. So let me then know if you make it. Thank you!

**Closed as completed** 2024-05-15 15:02 UTC
